import argparse
import subprocess
import sys
import time
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Watch a Raspberry Pi noise.csv file and upload it automatically after it becomes stable."
    )
    parser.add_argument("--noise-csv", required=True, help="Path to the noise.csv generated by GNU Radio / USRP.")
    parser.add_argument(
        "--uploader-script",
        default="upload_noise_csv.py",
        help="Path to upload_noise_csv.py on the Raspberry Pi.",
    )
    parser.add_argument("--api-url", required=True, help="Laptop upload endpoint, e.g. http://192.168.50.95:8888/api/usrp/upload-noise-csv")
    parser.add_argument("--scene", default="NTPU")
    parser.add_argument("--mission-id", required=True)
    parser.add_argument("--map-type", default="iss", choices=["sinr", "iss", "tss", "cfar"])
    parser.add_argument("--device-id", default="usrp-b210-sensor")
    parser.add_argument("--device-name", default="USRP B210 Sensor")
    parser.add_argument("--device-type", default="uav")
    parser.add_argument("--role", default="rx", choices=["rx", "tx", "jammer"])
    parser.add_argument("--devices-file", default="")
    parser.add_argument("--python-exe", default=sys.executable)
    parser.add_argument("--poll-seconds", type=float, default=2.0)
    parser.add_argument("--stable-seconds", type=float, default=5.0)
    parser.add_argument("--auto-simulate-last", action="store_true")
    parser.add_argument(
        "--state-file",
        default="",
        help="Optional path to persist the last uploaded file signature.",
    )
    return parser.parse_args()


def file_signature(path: Path) -> tuple[int, int]:
    stat = path.stat()
    return stat.st_size, stat.st_mtime_ns


def load_state(path: Path) -> tuple[int, int] | None:
    if not path.exists():
        return None
    raw = path.read_text(encoding="utf-8").strip()
    if not raw:
        return None
    size_str, mtime_str = raw.split(",", 1)
    return int(size_str), int(mtime_str)


def save_state(path: Path, signature: tuple[int, int]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"{signature[0]},{signature[1]}", encoding="utf-8")


def build_upload_command(args: argparse.Namespace, noise_csv: Path) -> list[str]:
    cmd = [
        args.python_exe,
        str(Path(args.uploader_script)),
        "--api-url",
        args.api_url,
        "--scene",
        args.scene,
        "--mission-id",
        args.mission_id,
        "--noise-csv",
        str(noise_csv),
        "--map-type",
        args.map_type,
        "--device-id",
        args.device_id,
        "--device-name",
        args.device_name,
        "--device-type",
        args.device_type,
        "--role",
        args.role,
    ]
    if args.devices_file:
        cmd.extend(["--devices-file", args.devices_file])
    if args.auto_simulate_last:
        cmd.append("--auto-simulate-last")
    return cmd


def main() -> int:
    args = parse_args()
    noise_csv = Path(args.noise_csv).resolve()
    uploader_script = Path(args.uploader_script).resolve()
    state_file = Path(args.state_file).resolve() if args.state_file else noise_csv.with_suffix(".upload_state")

    if not uploader_script.exists():
        print(f"uploader script not found: {uploader_script}", file=sys.stderr)
        return 1

    last_seen_signature: tuple[int, int] | None = None
    last_seen_at = 0.0
    uploaded_signature = load_state(state_file)

    print(f"[noise-watch] watching {noise_csv}")
    print(f"[noise-watch] uploader {uploader_script}")
    print(f"[noise-watch] state file {state_file}")

    while True:
        if not noise_csv.exists():
            time.sleep(args.poll_seconds)
            continue

        try:
            signature = file_signature(noise_csv)
        except FileNotFoundError:
            time.sleep(args.poll_seconds)
            continue

        now = time.time()
        if signature != last_seen_signature:
            last_seen_signature = signature
            last_seen_at = now
            print(f"[noise-watch] observed change size={signature[0]} mtime_ns={signature[1]}")
            time.sleep(args.poll_seconds)
            continue

        stable_for = now - last_seen_at
        if stable_for < args.stable_seconds:
            time.sleep(args.poll_seconds)
            continue

        if signature == uploaded_signature:
            time.sleep(args.poll_seconds)
            continue

        cmd = build_upload_command(args, noise_csv)
        print(f"[noise-watch] uploading stable file after {stable_for:.1f}s")
        proc = subprocess.run(cmd, check=False)
        if proc.returncode == 0:
            uploaded_signature = signature
            save_state(state_file, signature)
            print("[noise-watch] upload complete")
        else:
            print(f"[noise-watch] upload failed with exit code {proc.returncode}", file=sys.stderr)
        time.sleep(args.poll_seconds)


if __name__ == "__main__":
    raise SystemExit(main())
